"""SQL queries for pulling historical data from Snowflake."""

# SQLs Created by Team (Monthly)
SQLS_CREATED_QUERY = """
SELECT
    DATE_TRUNC('MONTH', OPPORTUNITY_CREATED_DATE)    AS MONTH,
    TEAM_NAME,
    CASE WHEN LEADSOURCE = 'IDEXX REFERRAL' THEN 'VDC' ELSE 'Other Leads' END AS LEAD_SOURCE_GROUP,
    COUNT(DISTINCT OPPORTUNITY_ID)                   AS SQLS_CREATED
FROM VSSANALYTICS_DB.SFDC.CDL_SALESFORCE
WHERE OPPORTUNITY_CREATED_DATE IS NOT NULL
  AND (
      (TEAM_NAME = 'ISAS' AND PRODUCT = 'Vello')
      OR (TEAM_NAME IN ('SOFTWARE SALES EAST', 'SOFTWARE SALES WEST')
          AND PRODUCT IN ('ezyVet', 'Neo', 'Vello'))
      OR (TEAM_NAME = 'ESAM'
          AND PRODUCT IN ('ezyVet', 'ezyVet Enterprise - GP', 'ezyVet Enterprise - Spec/ER'))
  )
GROUP BY 1, 2, 3
ORDER BY 2, 3, 1
"""

# Conversion Rates by Team & Lead Source (Rolling 18-Month Window)
CONVERSION_RATES_QUERY = """
WITH months AS (
    SELECT DATEADD('MONTH', SEQ4(), '2020-01-01')::DATE AS REPORTING_MONTH
    FROM TABLE(GENERATOR(ROWCOUNT => 200))
    WHERE DATEADD('MONTH', SEQ4(), '2020-01-01') <= DATE_TRUNC('MONTH', CURRENT_DATE())
),
opps AS (
    SELECT
        TEAM_NAME,
        CASE WHEN LEADSOURCE = 'IDEXX REFERRAL' THEN 'VDC' ELSE 'Other Leads' END AS LEAD_SOURCE_GROUP,
        OPPORTUNITY_ID,
        CURRENT_STAGE,
        OPPORTUNITY_CREATED_DATE,
        ACTUAL_CLOSE_DATE
    FROM VSSANALYTICS_DB.SFDC.CDL_SALESFORCE
    WHERE (
          (TEAM_NAME = 'ISAS' AND PRODUCT = 'Vello')
          OR (TEAM_NAME IN ('SOFTWARE SALES EAST', 'SOFTWARE SALES WEST')
              AND PRODUCT IN ('ezyVet', 'Neo', 'Vello'))
          OR (TEAM_NAME = 'ESAM'
              AND PRODUCT IN ('ezyVet', 'ezyVet Enterprise - GP', 'ezyVet Enterprise - Spec/ER'))
      )
),
monthly_conv AS (
    SELECT
        m.REPORTING_MONTH,
        o.TEAM_NAME,
        o.LEAD_SOURCE_GROUP,
        COUNT(DISTINCT CASE WHEN o.CURRENT_STAGE = 'WON' THEN o.OPPORTUNITY_ID END)        AS WINS,
        COUNT(DISTINCT CASE WHEN o.CURRENT_STAGE = 'CANCELLED' THEN o.OPPORTUNITY_ID END)  AS CANCELS,
        COUNT(DISTINCT CASE WHEN o.CURRENT_STAGE = 'LOST' THEN o.OPPORTUNITY_ID END)       AS LOST,
        COUNT(DISTINCT CASE WHEN o.CURRENT_STAGE NOT IN ('WON','CANCELLED','LOST','CAG PARENT CLOSED')
            AND DATEDIFF('DAY', o.OPPORTUNITY_CREATED_DATE, LAST_DAY(m.REPORTING_MONTH)) >= 180
            THEN o.OPPORTUNITY_ID END)                                                     AS OPEN_180_PLUS,
        COUNT(DISTINCT CASE WHEN o.CURRENT_STAGE NOT IN ('WON','CANCELLED','LOST','CAG PARENT CLOSED')
            AND DATEDIFF('DAY', o.OPPORTUNITY_CREATED_DATE, LAST_DAY(m.REPORTING_MONTH)) < 180
            THEN o.OPPORTUNITY_ID END)                                                     AS OPEN_ACTIVE
    FROM months m
    JOIN opps o
      ON (o.OPPORTUNITY_CREATED_DATE >= DATEADD('MONTH', -18, m.REPORTING_MONTH)
          AND o.OPPORTUNITY_CREATED_DATE < DATEADD('MONTH', 1, m.REPORTING_MONTH))
      OR (o.ACTUAL_CLOSE_DATE >= DATEADD('MONTH', -18, m.REPORTING_MONTH)
          AND o.ACTUAL_CLOSE_DATE < DATEADD('MONTH', 1, m.REPORTING_MONTH))
    GROUP BY 1, 2, 3
)
SELECT
    REPORTING_MONTH,
    TEAM_NAME,
    LEAD_SOURCE_GROUP,
    WINS,
    CANCELS,
    LOST,
    OPEN_180_PLUS,
    OPEN_ACTIVE,
    WINS + CANCELS + LOST + OPEN_180_PLUS                                                  AS RESOLVED_TOTAL,
    ROUND(100.0 * WINS / NULLIF(WINS + CANCELS + LOST + OPEN_180_PLUS, 0), 1)             AS CONVERSION_RATE_PCT
FROM monthly_conv
ORDER BY 2, 3, 1
"""

# Vello Placements by Month (GuideCX Onboarding)
VELLO_PLACEMENTS_QUERY = """
SELECT
    DATE_TRUNC('MONTH', CF_GO_LIVE_DATE)    AS MONTH,
    COUNT(DISTINCT PROJECT_ID)              AS VELLO_PLACEMENTS
FROM VSSANALYTICS_DB.GUIDECX.CDL_ONBOARDING
WHERE VELLO_BOOLEAN = 1
  AND CF_GO_LIVE_DATE IS NOT NULL
  AND STATUS NOT IN ('CANCELLED','ON_HOLD')
GROUP BY 1
ORDER BY 1
"""

# Time to Booking by Month
TIME_TO_BOOKING_QUERY = """
SELECT
    DATE_TRUNC('MONTH', ACTUAL_CLOSE_DATE)                              AS MONTH,
    TEAM_NAME,
    CASE WHEN LEADSOURCE = 'IDEXX REFERRAL' THEN 'VDC' ELSE 'Other Leads' END AS LEAD_SOURCE_GROUP,
    COUNT(DISTINCT OPPORTUNITY_ID)                                      AS BOOKINGS,
    ROUND(AVG(DATEDIFF('DAY', OPPORTUNITY_CREATED_DATE, ACTUAL_CLOSE_DATE)), 1) AS AVG_DAYS_TO_BOOKING,
    ROUND(MEDIAN(DATEDIFF('DAY', OPPORTUNITY_CREATED_DATE, ACTUAL_CLOSE_DATE)), 1) AS MEDIAN_DAYS_TO_BOOKING
FROM VSSANALYTICS_DB.SFDC.CDL_SALESFORCE
WHERE CURRENT_STAGE = 'WON'
  AND ACTUAL_CLOSE_DATE IS NOT NULL
  AND OPPORTUNITY_CREATED_DATE IS NOT NULL
  AND (
      (TEAM_NAME = 'ISAS' AND PRODUCT = 'Vello')
      OR (TEAM_NAME IN ('SOFTWARE SALES EAST', 'SOFTWARE SALES WEST')
          AND PRODUCT IN ('ezyVet', 'Neo', 'Vello'))
      OR (TEAM_NAME = 'ESAM'
          AND PRODUCT IN ('ezyVet', 'ezyVet Enterprise - GP', 'ezyVet Enterprise - Spec/ER'))
  )
GROUP BY 1, 2, 3
ORDER BY 2, 3, 1
"""

# Time to Placement by Month
TIME_TO_PLACEMENT_QUERY = """
SELECT
    DATE_TRUNC('MONTH', CF_GO_LIVE_DATE)                                AS MONTH,
    CF_PRODUCT                                                          AS PRODUCT,
    COUNT(DISTINCT PROJECT_ID)                                          AS PLACEMENTS,
    ROUND(AVG(DATEDIFF('DAY', CREATED_DATE, CF_GO_LIVE_DATE)), 1)      AS AVG_DAYS_TO_PLACEMENT,
    ROUND(MEDIAN(DATEDIFF('DAY', CREATED_DATE, CF_GO_LIVE_DATE)), 1)   AS MEDIAN_DAYS_TO_PLACEMENT
FROM VSSANALYTICS_DB.GUIDECX.CDL_ONBOARDING
WHERE CF_GO_LIVE_DATE IS NOT NULL
  AND CREATED_DATE IS NOT NULL
  AND STATUS NOT IN ('CANCELLED','ON-HOLD')
  AND VELLO_BOOLEAN = 1
GROUP BY 1, 2
ORDER BY 2, 1
"""

# Vello Install Base by Month
INSTALL_BASE_QUERY = """
SELECT
    REPORTING_MONTH,
    COUNT(DISTINCT SAP_ID)    AS VELLO_INSTALL_BASE
FROM VSSANALYTICS_DB.VSSANALYTICS.CDL_INSTALL_BASE
WHERE PRODUCT = 'Vello'
GROUP BY 1
ORDER BY 1
"""

# Vello Churns by Month
CHURNS_QUERY = """
SELECT
    REPORTING_MONTH,
    COUNT(DISTINCT SAP_ID)    AS VELLO_CHURNS
FROM VSSANALYTICS_DB.OPERATIONS.CDL_ATTRITION
WHERE PRODUCT = 'Vello'
GROUP BY 1
ORDER BY 1
"""

# MQL + VDC Leads to Opportunity Conversion Rate
MQL_CONVERSION_QUERY = """
SELECT
    DATE_TRUNC('MONTH', CONTACT_RECENT_MQL_DATE)    AS MONTH,
    'MQL'                                           AS LEAD_SOURCE,
    CASE
        WHEN FLATTENED_PRODUCT IN ('ezyVet', 'Neo') THEN 'ezyVet + Neo'
        WHEN FLATTENED_PRODUCT = 'Vello' THEN 'Vello'
    END                                             AS PRODUCT_GROUP,
    COUNT(DISTINCT HUBSPOT_CONTACT_ID)              AS LEADS,
    COUNT(DISTINCT OPPORTUNITY_ID)                   AS OPPS_CREATED,
    ROUND(100.0 * COUNT(DISTINCT OPPORTUNITY_ID)
        / NULLIF(COUNT(DISTINCT HUBSPOT_CONTACT_ID), 0), 1) AS LEAD_TO_OPP_CONVERSION_PCT
FROM VSSANALYTICS_DB.STRATPLAN_ANALYSIS.HUBSPOT_TO_SALESFORCE_MAPPING
WHERE IS_MQL = TRUE
  AND FLATTENED_PRODUCT IN ('ezyVet', 'Neo', 'Vello')
  AND CONTACT_RECENT_MQL_DATE IS NOT NULL
GROUP BY 1, 2, 3
UNION ALL
SELECT
    DATE_TRUNC('MONTH', CREATEDDATE)                AS MONTH,
    'VDC'                                           AS LEAD_SOURCE,
    CASE
        WHEN PRODUCT IN ('ezyVet', 'Neo') THEN 'ezyVet + Neo'
        WHEN PRODUCT = 'Vello' THEN 'Vello'
    END                                             AS PRODUCT_GROUP,
    COUNT(DISTINCT ID)                               AS LEADS,
    NULL                                             AS OPPS_CREATED,
    NULL                                             AS LEAD_TO_OPP_CONVERSION_PCT
FROM VSSANALYTICS_DB.SFDC.SF_VDC_LEADS
WHERE PRODUCT IN ('ezyVet', 'Neo', 'Vello')
  AND CREATEDDATE IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 3, 2, 1
"""
